window.DADOS_INICIAIS = [
  {
    "id": 1,
    "timestamp": "18/09/2026 13:57:53",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Rua barao de cotegipe n447",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "O rotativo foi ótimo pra cidade, porém a taxa de 20 reais pós utilização é péssima, pq tem muitas pessoas que não sabem muito bem como funciona, os idosos principalmente, ent não é muito justo.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 2,
    "timestamp": "18/09/2026 13:58:53",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barão de Cotegipe 435",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Aumentar os minutos de tolerância, pelo menos 15 minutos",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 3,
    "timestamp": "18/09/2026 13:59:51",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Rua barao cotegipe 419",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 4,
    "timestamp": "18/09/2026 14:00:59",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Está Ótimo.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 5,
    "timestamp": "18/09/2026 14:02:32",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Rua barao de cotegipe, n384 a",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 6,
    "timestamp": "18/09/2026 14:05:23",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Foi muito bom .",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 7,
    "timestamp": "18/09/2026 14:07:46",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Morador da via",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "Facilitou muito a encontrar vagas .",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 8,
    "timestamp": "18/09/2026 14:08:14",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barão  de cotegipe",
    "satisfacao": 1,
    "facilidade_vagas": "Piorou.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Para comerciantes o movimento diminuiu MUITO",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 9,
    "timestamp": "18/09/2026 14:11:13",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Melhorou muito para o meu comércio,  pessoal acha vaga mais fácil para parar próximo às lojas .",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 10,
    "timestamp": "18/09/2026 14:12:36",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe n384",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Acha injusto a cobrança de 20 reais de pos utilização, tinha que ser cobrado o valor de mais uma hora e não de um diária.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 11,
    "timestamp": "18/09/2026 14:13:56",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de Cotegipe 797",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Nao",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 12,
    "timestamp": "18/09/2026 14:15:22",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "Caiu muito o movimento das lojas .",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 13,
    "timestamp": "18/09/2026 14:16:54",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "Para achar vagas facilitou , mais para o comércio piorou muito .",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 14,
    "timestamp": "18/09/2026 14:17:24",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Rua barao de cotegipe, n419",
    "satisfacao": 1,
    "facilidade_vagas": "Piorou.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço alto e pagamento confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Acha que o rotativo atrapalhou o movimento de clientes. Ele foi implementado muito de supetão, além de que não houveram explicações, tanto para os clientes quanto para os lojistas.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 15,
    "timestamp": "18/09/2026 14:17:25",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de Cotegipe 395",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Com relação ao atendimento, eles estão perdidos e faltam pessoas para atender, as pessoas também ficam perdidas com isso",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 16,
    "timestamp": "18/09/2026 14:18:44",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Para o comércio acho que não foi tão bom pois as pessoas evitam parar pelo fato de não saberem utilizar o Apple, ou de jao querer. Pagar mesmo .",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 17,
    "timestamp": "18/09/2026 14:21:13",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Morador da via",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Nenhuma crítica.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 18,
    "timestamp": "18/09/2026 14:21:28",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barão de Cotegipe 371B",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Muito bom",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 19,
    "timestamp": "18/09/2026 14:22:10",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Ficou Ótimo.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 20,
    "timestamp": "18/09/2026 14:23:21",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, n362",
    "satisfacao": 3,
    "facilidade_vagas": "Piorou.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço alto e pagamento confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Acha injusto a taxa de pós utilização, pq muita das vezes o aplicativo está fora do ar, ou o celular descarregou. Acha que tinha que diminuir esse valor de 20 reais.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 21,
    "timestamp": "18/09/2026 14:23:51",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 22,
    "timestamp": "18/09/2026 14:25:24",
    "nome": "",
    "idade": "",
    "contato": "",
    "documento": "",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe 457",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Tarifa de tolerância ABSURDO",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 23,
    "timestamp": "18/09/2026 14:32:51",
    "nome": "Dilene",
    "idade": "50",
    "contato": "32988321010",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, n356",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Acha que tem que aumentar o tempo de tolerância para 20 min.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 24,
    "timestamp": "18/09/2026 14:37:33",
    "nome": "Ataide junir",
    "idade": "40",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Crítica,  os motoboys precisam parar muito longe da farmácia,  mais os clientes gostaram .sugestão: implantar adesivos, ou cadastro  para os motoboys ,em serviço ,para que não seja necessário pagar o rotativo .",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 25,
    "timestamp": "18/09/2026 14:41:14",
    "nome": "Marcia Menezes",
    "idade": "61",
    "contato": "34411065",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de Cotegipe 335",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Foi bom para achar as vagas mas tem que terminar de implementar em todos os lugares",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 26,
    "timestamp": "18/09/2026 14:41:35",
    "nome": "Roberta",
    "idade": "36",
    "contato": "3441-4018",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, n314",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 27,
    "timestamp": "18/09/2026 14:41:53",
    "nome": "Leticia Amaral",
    "idade": "28",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Achei ótimo. Nenhuma crítica.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 28,
    "timestamp": "18/09/2026 14:44:12",
    "nome": "Lia",
    "idade": "39",
    "contato": "32999376790",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, n330",
    "satisfacao": 3,
    "facilidade_vagas": "Não mudou nada.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 29,
    "timestamp": "18/09/2026 14:45:21",
    "nome": "Valeria Vargas",
    "idade": "59",
    "contato": "34413734",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de Cotegipe 329",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Gostou muito",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 30,
    "timestamp": "18/09/2026 14:45:26",
    "nome": "Andrea oliveira",
    "idade": "40",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 31,
    "timestamp": "18/09/2026 14:48:05",
    "nome": "Paulo",
    "idade": "26",
    "contato": "32999820008",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 320",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "O aplicativo, podia melhorar, pq ele não foi muito bem explicado, principalmente para os idosos. Além de que é difícil encontrar os monitores.",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 32,
    "timestamp": "18/09/2026 14:50:39",
    "nome": "Amanda Guimarães",
    "idade": "27",
    "contato": "3234412705",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Tiradentes,  21",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 33,
    "timestamp": "18/09/2026 14:51:11",
    "nome": "Alexandra",
    "idade": "45",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "As pessoas estam mais apressadas para olhar os produtos , por conta do tempo isso prejudicou comércio,  valor para motos ainda está muito caro . Sugestão: tempo poderia ser maior , tanto de tolerância quanto o tempo do rotativo .",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 34,
    "timestamp": "18/09/2026 14:54:27",
    "nome": "Luan Souza",
    "idade": "35",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço alto, mas aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Valor para moto poderia ser menor",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 35,
    "timestamp": "18/09/2026 15:03:21",
    "nome": "Felipe",
    "idade": "21",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Melhorou pois  os moradores por perto vinham de carro , ocupando as vagas e os comerciantes não encontravam vaga . Hoje com rotativo ficou mais fácil de encontrar com mais facilidade as vagas .",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 36,
    "timestamp": "18/09/2026 15:05:25",
    "nome": "Lara Santos",
    "idade": "26",
    "contato": "32998406675",
    "documento": "Prefiro não informar",
    "endereco": "",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barão de Cotegipe",
    "satisfacao": 1,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Nao concorda com a implementação",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 37,
    "timestamp": "18/09/2026 15:12:23",
    "nome": "Gisele",
    "idade": "23",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Cotegipe",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "Achei ótimo",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 38,
    "timestamp": "18/09/2026 15:13:38",
    "nome": "Sandra",
    "idade": "30",
    "contato": "34410370",
    "documento": "Prefiro não informar",
    "endereco": "Cohab",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, n 282",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 39,
    "timestamp": "18/09/2026 15:16:38",
    "nome": "Imaculada Silveira Campana",
    "idade": "56",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Vila Esteves",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 321",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço alto e pagamento confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Tarifa do rotativo para carro alta,contrária a tarifa pós uso, 15 minutos de tolerância.",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 40,
    "timestamp": "18/09/2026 15:22:15",
    "nome": "Gabriela Santos",
    "idade": "24",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Tome Nogueira",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de Cotegipe, 307",
    "satisfacao": 2,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço alto, mas aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Moto ser isenta.",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Eletrônico",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 41,
    "timestamp": "18/09/2026 15:24:38",
    "nome": "Elker",
    "idade": "50",
    "contato": "34414926.",
    "documento": "Prefiro não informar",
    "endereco": "Cotegipe 96",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, n 256",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "Podia aumentar o tempo limite de 10 minutos para 20 min.",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Vestuário",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 42,
    "timestamp": "18/09/2026 15:25:17",
    "nome": "Matheus Guida",
    "idade": "32",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Cohab Nova",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe, 301",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Abaixou",
    "tipo_comercio": "Eletronicos",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 43,
    "timestamp": "18/09/2026 15:30:06",
    "nome": "Dilsiney",
    "idade": "57",
    "contato": "32998558231",
    "documento": "Prefiro não informar",
    "endereco": "Rua das flores",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 25",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Utilidade e brinquedos",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 44,
    "timestamp": "18/09/2026 15:31:19",
    "nome": "Carlos henrique",
    "idade": "41",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Tres cruzes",
    "perfil": "Motorista / Pedestre (visitante)",
    "local": "Cotegipe",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não se aplica (não é comerciante).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Eu não sabia que isso existia, mas acho uma excelente alternativa para evitar multas.",
    "sugestao_critica": "No início foi bem difícil o uso do App,mais agora está ótimo.",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "",
    "tipo_comercio": "",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 45,
    "timestamp": "18/09/2026 15:31:41",
    "nome": "Amaurides Machado",
    "idade": "62",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Cataguases",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe, 297",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil, mas o prazo de 3 dias para pagamento deveria ser maior.",
    "sugestao_critica": "Melhorar a questão da tarifa pós uso. Sem aplicar multa de 190 reais",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Aviamento e pedrarias",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 46,
    "timestamp": "18/09/2026 15:37:43",
    "nome": "Andreia",
    "idade": "48",
    "contato": "3298i335082",
    "documento": "Prefiro não informar",
    "endereco": "Vila esteves",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Rua barao de cotegipe, 237",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Tem q colocar mais monitores.",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Vestuários",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 47,
    "timestamp": "18/09/2026 15:44:14",
    "nome": "Maria Olimpia",
    "idade": "39",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Bandeirantes",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "277",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil, mas o prazo de 3 dias para pagamento deveria ser maior.",
    "sugestao_critica": "Aumentar o número de monitores",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Calçados",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 48,
    "timestamp": "18/09/2026 15:45:15",
    "nome": "Cristina",
    "idade": "50",
    "contato": "32999842818",
    "documento": "Prefiro não informar",
    "endereco": "Pirineus",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de xotegiep, 230",
    "satisfacao": 2,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "Houve muita falta de informações com relação a implementação do sistema, apesar de divulgar no Instagram, muitas pessoas não tem acesso. Além disso, seria bom aumentar o tempo de tolerância para uns 20 min, e tem aumentar o tempo, duas horas é muito pouco, muita das vezes a pessoa acaba tendo q pagar a multa por não ter tido como renovar por estar atendendo um cliente, por exemplo.",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Celulares",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 49,
    "timestamp": "18/09/2026 15:48:45",
    "nome": "Ariane",
    "idade": "22",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Pirineus",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe, 259",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil, mas o prazo de 3 dias para pagamento deveria ser maior.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Moveis e eletrodomesticos",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 50,
    "timestamp": "18/09/2026 15:57:46",
    "nome": "Julio",
    "idade": "58",
    "contato": "32999784655",
    "documento": "Prefiro não informar",
    "endereco": "Eldorado",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 230",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Houve muita falta de informação por parte da prefeitura, devia ter instruído melhor a população sobre como funciona. Além de que não ter colocado o rotativo em outras áreas, como a presidente Carlos Luz, esta afetando, pq as pessoas evitam parar na cotegipe e, consequentemente, acabam não entrando com mais facilidade nas lojas.\nSobre a questão do tempo de tolerância, seria bom explicar melhor sobre e aumentar o tempo. Pq tem muitas pessoas q param por 10 min e aproveita para fazer as coisas na rua, sendo q esse tempo é para pagar o aplicativo, prejudicando as vendas tbm, pq a pessoa para por 10 min e vai na loja somente para pegar uma coisa, não dando oportunidade para o vendedor oferecer outra coisa.",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Nao sabe informar, pq nao sabe se foi a crise econômica ou o rotativo.",
    "tipo_comercio": "Vestuários",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 51,
    "timestamp": "18/09/2026 16:04:13",
    "nome": "Keyce",
    "idade": "17",
    "contato": "32987902741",
    "documento": "Prefiro não informar",
    "endereco": "Fortaleza",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "N210",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "Melhorar os meios de informação sobre o rotativo",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Celulares",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 52,
    "timestamp": "18/09/2026 16:04:31",
    "nome": "Josiane",
    "idade": "37",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Pirineus",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe, 225",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Diminuiu",
    "tipo_comercio": "Roupas",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 53,
    "timestamp": "18/09/2026 16:08:01",
    "nome": "Suelen",
    "idade": "25",
    "contato": "32998800863",
    "documento": "Prefiro não informar",
    "endereco": "Sao Cristóvão",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, n210",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "30%",
    "tipo_comercio": "Vestuários",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 54,
    "timestamp": "18/09/2026 16:12:10",
    "nome": "César",
    "idade": "60",
    "contato": "34412279",
    "documento": "Prefiro não informar",
    "endereco": "Vila esteves",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe,  204",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo, mas aplicativo/pagamento é confuso.",
    "tarifa_pos_utilizacao": "Já conhecia, acho útil para evitar multa, mas considero os valores altos.",
    "sugestao_critica": "Aumentar o rotativo para outras ruas e diminuir o valor q é cobrado de 20 reais",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "Nao sabe dizer se foi por causa da crise ou do rotativo",
    "tipo_comercio": "Tecido",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 55,
    "timestamp": "18/09/2026 16:15:30",
    "nome": "Crislaine",
    "idade": "35",
    "contato": "32933005880",
    "documento": "Prefiro não informar",
    "endereco": "Ribeiro junqueira",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 186",
    "satisfacao": 4,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "-6%",
    "tipo_comercio": "Varejo",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 56,
    "timestamp": "18/09/2026 16:17:56",
    "nome": "Euler",
    "idade": "24",
    "contato": "34410732",
    "documento": "Prefiro não informar",
    "endereco": "Bela vista",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 180",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Já conhecia e acho o modelo excelente (valor justo e prazo adequado).",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Vestuários",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 57,
    "timestamp": "18/09/2026 16:20:54",
    "nome": "Glaucia",
    "idade": "31",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Caiçaras",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe, 217",
    "satisfacao": 2,
    "facilidade_vagas": "Sim, melhorou um pouco.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço alto, mas aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Rotativo somente na cotegipe",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Perfumaria",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 58,
    "timestamp": "18/09/2026 16:22:44",
    "nome": "Giane",
    "idade": "39",
    "contato": "34873040",
    "documento": "Prefiro não informar",
    "endereco": "Tome nogueira",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 164",
    "satisfacao": 1,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Não teve impacto no meu comércio.",
    "avaliacao_preco_app": "Preço alto e pagamento confuso.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Planos e aparelhos",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 59,
    "timestamp": "18/09/2026 16:29:39",
    "nome": "Bruna",
    "idade": "19",
    "contato": "",
    "documento": "Prefiro não informar",
    "endereco": "Sao Cristovao",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Cotegipe, 183",
    "satisfacao": 3,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Diminuiu o fluxo (clientes evitam pagar ou não sabem usar).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Desnecessário o rotativo, tempo de tolerância 15 minutos,",
    "pagou_pos_utilizacao": "Sim",
    "aumento_faturamento": "Diminuiu",
    "tipo_comercio": "Doces finos",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  },
  {
    "id": 60,
    "timestamp": "18/09/2026 16:34:59",
    "nome": "Marcos de souza",
    "idade": "48",
    "contato": "3234411684",
    "documento": "Prefiro não informar,",
    "endereco": "Centro",
    "perfil": "Comerciante / Funcionário de loja",
    "local": "Barao de cotegipe, 156 e 154",
    "satisfacao": 5,
    "facilidade_vagas": "Sim, melhorou muito.",
    "impacto_comercio": "Aumentou o fluxo (clientes encontram vaga mais fácil).",
    "avaliacao_preco_app": "Preço justo e aplicativo fácil de usar.",
    "tarifa_pos_utilizacao": "Sou contra esse formato de cobrança.",
    "sugestao_critica": "Os monitores andam muitos juntos, ou nunca estão nos locais, ou coloca só locais físicos ou os monitores precisam  ser separados por área. Precisa melhorar a questão de informações.",
    "pagou_pos_utilizacao": "Não",
    "aumento_faturamento": "Não sei informar",
    "tipo_comercio": "Vestuários",
    "outro": "",
    "pesquisa_onda": "Pesquisa 01 - Centro (Com Rotativo)"
  }
];